# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: oracle.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import (
    TYPE_CHECKING,
    Dict,
    List,
    Optional,
)

import betterproto
import grpclib
from betterproto.grpc.grpclib_server import ServiceBase


if TYPE_CHECKING:
    import grpclib.server
    from betterproto.grpc.grpclib_client import MetadataLike
    from grpclib.metadata import Deadline


@dataclass(eq=False, repr=False)
class TelemetryRequest(betterproto.Message):
    """Telemetry from smart meters, batteries, and virtual power plants"""

    reading_id: str = betterproto.string_field(1)
    meter_id: str = betterproto.string_field(2)
    meter_serial: str = betterproto.string_field(3)
    user_id: str = betterproto.string_field(4)
    wallet_address: str = betterproto.string_field(5)
    zone_code: Optional[str] = betterproto.string_field(17, optional=True)
    kwh: str = betterproto.string_field(7)
    energy_generated: Optional[str] = betterproto.string_field(8, optional=True)
    energy_consumed: Optional[str] = betterproto.string_field(9, optional=True)
    voltage: Optional[str] = betterproto.string_field(10, optional=True)
    current: Optional[str] = betterproto.string_field(11, optional=True)
    battery_level: Optional[str] = betterproto.string_field(12, optional=True)
    temperature: Optional[str] = betterproto.string_field(13, optional=True)
    timestamp: int = betterproto.int64_field(14)
    raw_payload: bytes = betterproto.bytes_field(15)
    signature: Optional[str] = betterproto.string_field(16, optional=True)


@dataclass(eq=False, repr=False)
class TelemetryResponse(betterproto.Message):
    receipt_id: str = betterproto.string_field(1)
    status: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class TelemetryBatchRequest(betterproto.Message):
    """Batch telemetry submission for high throughput"""

    readings: List["TelemetryRequest"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class TelemetryBatchResponse(betterproto.Message):
    receipt_ids: List[str] = betterproto.string_field(1)
    status: str = betterproto.string_field(2)
    accepted_count: int = betterproto.int32_field(3)
    rejected_count: int = betterproto.int32_field(4)


@dataclass(eq=False, repr=False)
class PullGlobalModelRequest(betterproto.Message):
    """Federated Learning: Request latest global model"""

    meter_id: str = betterproto.string_field(1)
    current_version: str = betterproto.string_field(2)
    model_type: str = betterproto.string_field(3)


@dataclass(eq=False, repr=False)
class PullGlobalModelResponse(betterproto.Message):
    version: str = betterproto.string_field(1)
    model_payload: bytes = betterproto.bytes_field(2)
    model_type: str = betterproto.string_field(3)
    timestamp: int = betterproto.int64_field(4)


@dataclass(eq=False, repr=False)
class PushGradientsRequest(betterproto.Message):
    """Federated Learning: Push local gradients"""

    meter_id: str = betterproto.string_field(1)
    base_version: str = betterproto.string_field(2)
    layers: Dict[str, "GradientLayer"] = betterproto.map_field(
        3, betterproto.TYPE_STRING, betterproto.TYPE_MESSAGE
    )
    sample_count: int = betterproto.int32_field(4)


@dataclass(eq=False, repr=False)
class GradientLayer(betterproto.Message):
    values: List[float] = betterproto.float_field(1)


@dataclass(eq=False, repr=False)
class PushGradientsResponse(betterproto.Message):
    status: str = betterproto.string_field(1)
    accepted: bool = betterproto.bool_field(2)


class OracleServiceStub(betterproto.ServiceStub):
    async def submit_telemetry(
        self,
        telemetry_request: "TelemetryRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "TelemetryResponse":
        return await self._unary_unary(
            "/gridtokenx.oracle.v1.OracleService/SubmitTelemetry",
            telemetry_request,
            TelemetryResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def submit_telemetry_batch(
        self,
        telemetry_batch_request: "TelemetryBatchRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "TelemetryBatchResponse":
        return await self._unary_unary(
            "/gridtokenx.oracle.v1.OracleService/SubmitTelemetryBatch",
            telemetry_batch_request,
            TelemetryBatchResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def push_gradients(
        self,
        push_gradients_request: "PushGradientsRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "PushGradientsResponse":
        return await self._unary_unary(
            "/gridtokenx.oracle.v1.OracleService/PushGradients",
            push_gradients_request,
            PushGradientsResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def pull_global_model(
        self,
        pull_global_model_request: "PullGlobalModelRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "PullGlobalModelResponse":
        return await self._unary_unary(
            "/gridtokenx.oracle.v1.OracleService/PullGlobalModel",
            pull_global_model_request,
            PullGlobalModelResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class OracleServiceBase(ServiceBase):

    async def submit_telemetry(
        self, telemetry_request: "TelemetryRequest"
    ) -> "TelemetryResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def submit_telemetry_batch(
        self, telemetry_batch_request: "TelemetryBatchRequest"
    ) -> "TelemetryBatchResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def push_gradients(
        self, push_gradients_request: "PushGradientsRequest"
    ) -> "PushGradientsResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def pull_global_model(
        self, pull_global_model_request: "PullGlobalModelRequest"
    ) -> "PullGlobalModelResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_submit_telemetry(
        self, stream: "grpclib.server.Stream[TelemetryRequest, TelemetryResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.submit_telemetry(request)
        await stream.send_message(response)

    async def __rpc_submit_telemetry_batch(
        self,
        stream: "grpclib.server.Stream[TelemetryBatchRequest, TelemetryBatchResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.submit_telemetry_batch(request)
        await stream.send_message(response)

    async def __rpc_push_gradients(
        self,
        stream: "grpclib.server.Stream[PushGradientsRequest, PushGradientsResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.push_gradients(request)
        await stream.send_message(response)

    async def __rpc_pull_global_model(
        self,
        stream: "grpclib.server.Stream[PullGlobalModelRequest, PullGlobalModelResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.pull_global_model(request)
        await stream.send_message(response)

    def __mapping__(self) -> Dict[str, grpclib.const.Handler]:
        return {
            "/gridtokenx.oracle.v1.OracleService/SubmitTelemetry": grpclib.const.Handler(
                self.__rpc_submit_telemetry,
                grpclib.const.Cardinality.UNARY_UNARY,
                TelemetryRequest,
                TelemetryResponse,
            ),
            "/gridtokenx.oracle.v1.OracleService/SubmitTelemetryBatch": grpclib.const.Handler(
                self.__rpc_submit_telemetry_batch,
                grpclib.const.Cardinality.UNARY_UNARY,
                TelemetryBatchRequest,
                TelemetryBatchResponse,
            ),
            "/gridtokenx.oracle.v1.OracleService/PushGradients": grpclib.const.Handler(
                self.__rpc_push_gradients,
                grpclib.const.Cardinality.UNARY_UNARY,
                PushGradientsRequest,
                PushGradientsResponse,
            ),
            "/gridtokenx.oracle.v1.OracleService/PullGlobalModel": grpclib.const.Handler(
                self.__rpc_pull_global_model,
                grpclib.const.Cardinality.UNARY_UNARY,
                PullGlobalModelRequest,
                PullGlobalModelResponse,
            ),
        }
