# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: oracle.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import (
    TYPE_CHECKING,
    Dict,
    List,
    Optional,
)

import betterproto
import grpclib
from betterproto.grpc.grpclib_server import ServiceBase


if TYPE_CHECKING:
    import grpclib.server
    from betterproto.grpc.grpclib_client import MetadataLike
    from grpclib.metadata import Deadline


@dataclass(eq=False, repr=False)
class MeterReading(betterproto.Message):
    """Canonical Meter Reading with integrated security"""

    reading_id: str = betterproto.string_field(1)
    meter_id: str = betterproto.string_field(2)
    meter_serial: str = betterproto.string_field(3)
    user_id: str = betterproto.string_field(4)
    wallet_address: str = betterproto.string_field(5)
    zone_code: Optional[str] = betterproto.string_field(6, optional=True)
    kwh: str = betterproto.string_field(7)
    """Energy metrics"""

    energy_generated: Optional[str] = betterproto.string_field(8, optional=True)
    energy_consumed: Optional[str] = betterproto.string_field(9, optional=True)
    voltage: Optional[str] = betterproto.string_field(10, optional=True)
    """Operational metrics"""

    current: Optional[str] = betterproto.string_field(11, optional=True)
    battery_level: Optional[str] = betterproto.string_field(12, optional=True)
    temperature: Optional[str] = betterproto.string_field(13, optional=True)
    timestamp: int = betterproto.int64_field(14)
    raw_payload: bytes = betterproto.bytes_field(15)
    signature: Optional[str] = betterproto.string_field(16, optional=True)


@dataclass(eq=False, repr=False)
class IngestResponse(betterproto.Message):
    receipt_id: str = betterproto.string_field(1)
    status: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class MeterReadingBatchRequest(betterproto.Message):
    readings: List["MeterReading"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class MeterReadingBatchResponse(betterproto.Message):
    receipt_ids: List[str] = betterproto.string_field(1)
    status: str = betterproto.string_field(2)
    accepted_count: int = betterproto.int32_field(3)
    rejected_count: int = betterproto.int32_field(4)


class OracleServiceStub(betterproto.ServiceStub):
    async def ingest(
        self,
        meter_reading: "MeterReading",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "IngestResponse":
        return await self._unary_unary(
            "/gridtokenx.oracle.v1.OracleService/Ingest",
            meter_reading,
            IngestResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def ingest_batch(
        self,
        meter_reading_batch_request: "MeterReadingBatchRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "MeterReadingBatchResponse":
        return await self._unary_unary(
            "/gridtokenx.oracle.v1.OracleService/IngestBatch",
            meter_reading_batch_request,
            MeterReadingBatchResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class OracleServiceBase(ServiceBase):

    async def ingest(self, meter_reading: "MeterReading") -> "IngestResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def ingest_batch(
        self, meter_reading_batch_request: "MeterReadingBatchRequest"
    ) -> "MeterReadingBatchResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_ingest(
        self, stream: "grpclib.server.Stream[MeterReading, IngestResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.ingest(request)
        await stream.send_message(response)

    async def __rpc_ingest_batch(
        self,
        stream: "grpclib.server.Stream[MeterReadingBatchRequest, MeterReadingBatchResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.ingest_batch(request)
        await stream.send_message(response)

    def __mapping__(self) -> Dict[str, grpclib.const.Handler]:
        return {
            "/gridtokenx.oracle.v1.OracleService/Ingest": grpclib.const.Handler(
                self.__rpc_ingest,
                grpclib.const.Cardinality.UNARY_UNARY,
                MeterReading,
                IngestResponse,
            ),
            "/gridtokenx.oracle.v1.OracleService/IngestBatch": grpclib.const.Handler(
                self.__rpc_ingest_batch,
                grpclib.const.Cardinality.UNARY_UNARY,
                MeterReadingBatchRequest,
                MeterReadingBatchResponse,
            ),
        }
