"""Guards on the electrical data in the shipped CINELDI reference GLMs.

All four are generated by `scripts/regen_reference_glm.py` from the published
CSVs. An earlier revision of `scripts/export_glm.py` wrote connectivity only, so
the model built with it silently ran on the uniform `LINE_*` impedance fallbacks
and had no thermal ratings at all -- and nothing failed. These tests exist so
that regression cannot come back quietly: a re-export that drops the electrical
data changes no count and raises no validation error, it just makes the feeder
look several times stiffer than it is.
"""

import asyncio
from pathlib import Path

import pytest

from smart_meter_simulator.adapters.glm_topology_loader import load_glm_topology
from smart_meter_simulator.core.engine import SimulationEngine

GRID_DIR = Path("src/smart_meter_simulator/data/grids")
REFERENCE_GLM_FILE = GRID_DIR / "grid_bus_network.glm"

# The default reference grid plus the other three published CINELDI grids.
GRID_FILES = [
    REFERENCE_GLM_FILE,
    GRID_DIR / "cineldi_50_bus_rural.glm",
    GRID_DIR / "cineldi_39_bus_semi_urban.glm",
    GRID_DIR / "cineldi_56_bus_semi_urban.glm",
]

# The env fallbacks that a GLM without impedance silently lands on.
FALLBACK_R_OHM_PER_KM = 0.125
FALLBACK_X_OHM_PER_KM = 0.08

# Published conductors span ~0.125-3.1 ohm/km across the four grids: 240 mm2
# aluminium trunks in the semi-urban networks at the bottom, 25 mm2 rural
# laterals at the top.
MIN_PLAUSIBLE_R = 0.12
MAX_PLAUSIBLE_R = 3.5


@pytest.fixture(scope="module")
def topologies():
    return {path.stem: load_glm_topology(str(path)) for path in GRID_FILES}


@pytest.fixture(params=[path.stem for path in GRID_FILES])
def topology(request, topologies):
    return topologies[request.param]


def test_every_line_carries_its_own_impedance(topology):
    missing = [line.name for line in topology.lines if line.resistance_ohm_per_km <= 0]
    assert not missing, f"lines with no impedance (will use LINE_* fallbacks): {missing}"

    out_of_range = [
        (line.name, line.resistance_ohm_per_km)
        for line in topology.lines
        if not MIN_PLAUSIBLE_R <= line.resistance_ohm_per_km <= MAX_PLAUSIBLE_R
    ]
    assert not out_of_range, f"implausible r for LV conductor: {out_of_range}"


def test_impedance_is_not_the_uniform_fallback(topology):
    """The tell-tale of a connectivity-only export: every line identical."""
    resistances = {round(line.resistance_ohm_per_km, 6) for line in topology.lines}
    assert len(resistances) > 1, "all lines share one resistance -- impedance was dropped"
    assert resistances != {FALLBACK_R_OHM_PER_KM}
    reactances = {round(line.reactance_ohm_per_km, 6) for line in topology.lines}
    assert reactances != {FALLBACK_X_OHM_PER_KM}


def test_every_line_carries_a_thermal_rating(topology):
    unrated = [line.name for line in topology.lines if line.capacity_kw <= 0]
    assert not unrated, f"lines with no capacity_kw (rateA was dropped): {unrated}"


def test_transformers_are_sized(topology):
    assert topology.transformers, "no PCC transformers -- every bus would be unzoned"
    for trafo in topology.transformers:
        assert trafo.sn_mva > 0, f"{trafo.name} has no rating"
        assert trafo.vk_percent > 0, f"{trafo.name} has no short-circuit impedance"
        assert 0 < trafo.vkr_percent < trafo.vk_percent


@pytest.mark.parametrize("path", GRID_FILES, ids=lambda p: p.stem)
def test_feeder_end_voltage_stays_within_en_50160(path):
    engine = SimulationEngine(grid_topology=f"glm:{path}", num_meters=40)
    engine.grid.initialize_network(engine.meters)
    asyncio.run(engine.tick())

    vm = engine.grid.pp_net.res_bus.vm_pu.dropna()
    assert vm.min() >= 0.90, f"under-voltage at the feeder end: {vm.min():.4f} pu"


def test_reference_grid_is_not_implausibly_stiff():
    """Losing the impedance makes the far end look *better*, not worse -- 0.9591 pu
    against the real 0.9019 -- so a one-sided >= 0.90 assertion would never catch
    the regression it is there for. The rural 80-bus is the grid where the two are
    far enough apart to bound from above: 5 km of thin LV cable has to cost
    something. The semi-urban grids are genuinely stiff (0.98+) and get no upper
    bound."""
    engine = SimulationEngine(
        grid_topology=f"glm:{REFERENCE_GLM_FILE}", num_meters=40
    )
    engine.grid.initialize_network(engine.meters)
    asyncio.run(engine.tick())

    vmin = engine.grid.pp_net.res_bus.vm_pu.dropna().min()
    assert vmin < 0.95, (
        f"feeder end at {vmin:.4f} pu is too stiff for 5 km of LV cable -- "
        "impedance is probably back on the uniform fallback"
    )
