"""Guards on the electrical data in the shipped reference GLM.

`grid_bus_network.glm` is generated by `scripts/regen_reference_glm.py` from the
CINELDI 80-bus rural CSVs. An earlier revision of `scripts/export_glm.py` wrote
connectivity only, so the model silently ran on the uniform `LINE_*` impedance
fallbacks and had no thermal ratings at all -- and nothing failed. These tests
exist so that regression cannot come back quietly: a re-export that drops the
electrical data changes no count and raises no validation error, it just makes
the feeder look several times stiffer than it is.
"""

import asyncio
from pathlib import Path

import pytest

from smart_meter_simulator.adapters.glm_topology_loader import load_glm_topology
from smart_meter_simulator.core.engine import SimulationEngine

REFERENCE_GLM_FILE = Path("src/smart_meter_simulator/data/grids/grid_bus_network.glm")

# The env fallbacks that a GLM without impedance silently lands on.
FALLBACK_R_OHM_PER_KM = 0.125
FALLBACK_X_OHM_PER_KM = 0.08

# EX 3x25/50/95 Al as published: r spans ~0.13-3.1 ohm/km once the per-branch
# values are carried through, x sits an order of magnitude below it.
MIN_PLAUSIBLE_R = 0.12
MAX_PLAUSIBLE_R = 3.5


@pytest.fixture(scope="module")
def topology():
    return load_glm_topology(str(REFERENCE_GLM_FILE))


def test_every_line_carries_its_own_impedance(topology):
    missing = [line.name for line in topology.lines if line.resistance_ohm_per_km <= 0]
    assert not missing, f"lines with no impedance (will use LINE_* fallbacks): {missing}"

    out_of_range = [
        (line.name, line.resistance_ohm_per_km)
        for line in topology.lines
        if not MIN_PLAUSIBLE_R <= line.resistance_ohm_per_km <= MAX_PLAUSIBLE_R
    ]
    assert not out_of_range, f"implausible r for LV Al conductor: {out_of_range}"


def test_impedance_is_not_the_uniform_fallback(topology):
    """The tell-tale of a connectivity-only export: every line identical."""
    resistances = {round(line.resistance_ohm_per_km, 6) for line in topology.lines}
    assert len(resistances) > 1, "all lines share one resistance -- impedance was dropped"
    assert resistances != {FALLBACK_R_OHM_PER_KM}
    reactances = {round(line.reactance_ohm_per_km, 6) for line in topology.lines}
    assert reactances != {FALLBACK_X_OHM_PER_KM}


def test_every_line_carries_a_thermal_rating(topology):
    unrated = [line.name for line in topology.lines if line.capacity_kw <= 0]
    assert not unrated, f"lines with no capacity_kw (rateA was dropped): {unrated}"


def test_transformers_are_sized(topology):
    assert len(topology.transformers) == 3
    for trafo in topology.transformers:
        assert trafo.sn_mva > 0, f"{trafo.name} has no rating"
        assert trafo.vk_percent > 0, f"{trafo.name} has no short-circuit impedance"
        assert 0 < trafo.vkr_percent < trafo.vk_percent


def test_feeder_end_voltage_stays_within_en_50160():
    """With the real conductors the far end sags to ~0.90 pu, and the OLTC is
    what keeps it legal. Both halves matter: too high means the impedance went
    missing again, too low means the tap can no longer hold the feeder up."""
    engine = SimulationEngine(
        grid_topology=f"glm:{REFERENCE_GLM_FILE}", num_meters=40
    )
    engine.grid.initialize_network(engine.meters)
    asyncio.run(engine.tick())

    vm = engine.grid.pp_net.res_bus.vm_pu.dropna()
    assert vm.min() >= 0.90, f"under-voltage at the feeder end: {vm.min():.4f} pu"
    assert vm.min() < 0.95, (
        f"feeder end at {vm.min():.4f} pu is too stiff for 5 km of LV cable -- "
        "impedance is probably back on the uniform fallback"
    )
