persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log

# Port 1883 for internal communication
listener 1883
allow_anonymous true

# Port 9001 for WebSocket connections (Dashboards)
listener 9001
protocol websockets
allow_anonymous true
