# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import oracle_pb2 as oracle__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in oracle_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OracleServiceStub:
    """Service for high-performance unified oracle ingestion (UTT)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ingest = channel.unary_unary(
                '/gridtokenx.oracle.v1.OracleService/Ingest',
                request_serializer=oracle__pb2.MeterReading.SerializeToString,
                response_deserializer=oracle__pb2.IngestResponse.FromString,
                _registered_method=True)
        self.IngestBatch = channel.unary_unary(
                '/gridtokenx.oracle.v1.OracleService/IngestBatch',
                request_serializer=oracle__pb2.MeterReadingBatchRequest.SerializeToString,
                response_deserializer=oracle__pb2.MeterReadingBatchResponse.FromString,
                _registered_method=True)
        self.BulkRawIngest = channel.unary_unary(
                '/gridtokenx.oracle.v1.OracleService/BulkRawIngest',
                request_serializer=oracle__pb2.BulkRawRequest.SerializeToString,
                response_deserializer=oracle__pb2.BulkRawResponse.FromString,
                _registered_method=True)


class OracleServiceServicer:
    """Service for high-performance unified oracle ingestion (UTT)
    """

    def Ingest(self, request, context):
        """Unified Ingestion: Verified telemetry for both VPP operations (Path A) and Settlement (Path B)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IngestBatch(self, request, context):
        """Batch Ingestion: Optimized for high-throughput aggregators
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BulkRawIngest(self, request, context):
        """Bulk Raw Ingestion: Maximum performance endpoint for simulators (bypasses per-reading Protobuf overhead)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OracleServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ingest': grpc.unary_unary_rpc_method_handler(
                    servicer.Ingest,
                    request_deserializer=oracle__pb2.MeterReading.FromString,
                    response_serializer=oracle__pb2.IngestResponse.SerializeToString,
            ),
            'IngestBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestBatch,
                    request_deserializer=oracle__pb2.MeterReadingBatchRequest.FromString,
                    response_serializer=oracle__pb2.MeterReadingBatchResponse.SerializeToString,
            ),
            'BulkRawIngest': grpc.unary_unary_rpc_method_handler(
                    servicer.BulkRawIngest,
                    request_deserializer=oracle__pb2.BulkRawRequest.FromString,
                    response_serializer=oracle__pb2.BulkRawResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gridtokenx.oracle.v1.OracleService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gridtokenx.oracle.v1.OracleService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OracleService:
    """Service for high-performance unified oracle ingestion (UTT)
    """

    @staticmethod
    def Ingest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gridtokenx.oracle.v1.OracleService/Ingest',
            oracle__pb2.MeterReading.SerializeToString,
            oracle__pb2.IngestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IngestBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gridtokenx.oracle.v1.OracleService/IngestBatch',
            oracle__pb2.MeterReadingBatchRequest.SerializeToString,
            oracle__pb2.MeterReadingBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BulkRawIngest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gridtokenx.oracle.v1.OracleService/BulkRawIngest',
            oracle__pb2.BulkRawRequest.SerializeToString,
            oracle__pb2.BulkRawResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
