export const LOG_MAX_ENTRIES = 100;
export const WS_RECONNECT_DELAY_MS = 5000;
export const STATUS_REFRESH_DELAY_MS = 1000;
export const DEFAULT_METER_COUNT = 20;
export const DEFAULT_ITEMS_PER_PAGE_GRID = 6;
export const DEFAULT_ITEMS_PER_PAGE_LIST = 10;
