[package]
name = "gridtokenx-py"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "gridtokenx_py"
crate-type = ["cdylib"]

[workspace]

[dependencies]
pyo3 = { version = "0.22.0", features = ["extension-module"] }
solana-zk-token-sdk = "1.18.26"
curve25519-dalek = { version = "3", features = ["serde"] }
rand = "0.8"
base64 = "0.21"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bytemuck = { version = "1.16", features = ["derive"] }
